FROM golang:1.26-alpine

RUN apk add --no-cache make fish

COPY ["./cmd", "/project/network-uci-bridge/cmd"]
COPY ["./pkg", "/project/network-uci-bridge/pkg"]
COPY ["./go.mod", "./Makefile", "/project/network-uci-bridge/"]

WORKDIR "/project/network-uci-bridge"

CMD ["/usr/bin/fish"]